---
#
# https://aaronsaray.com/2015/ansible-installation-of-postfix-with-no-prompts
# http://ryaneschinger.com/blog/securing-a-server-with-ansible/
#    dpkg-reconfigure exim4-config
#
# root@lester:/etc/ufw# debconf-get-selections | grep "exim4-config"  | more
# exim4-config  exim4/dc_eximconfig_configtype  select  mail sent by smarthost;
# exim4-config  exim4/mailname  string  lester.cybersecs.xyz
# exim4-config  exim4/no_config boolean true
# exim4-config  exim4/hide_mailname boolean true
# exim4-config  exim4/use_split_config  boolean false
# exim4-config  exim4/dc_relay_domains  string  
# exim4-config  exim4/dc_readhost   string  cybersecs.xyz
# exim4-config  exim4/dc_local_interfaces   string  192.168.1.111
# exim4-config  exim4/dc_minimaldns boolean false
# exim4-config  exim4/dc_relay_nets string  199.19.214.199/32
# exim4-config  exim4/dc_localdelivery  select  mbox format in /var/mail/
# exim4-config  exim4/dc_smarthost  string  smtp.cybersecs.xyz::3025
# exim4-config  exim4/dc_postmaster string  dannys
# exim4-config  exim4/dc_other_hostnames    string


- name: Setup postfix to relay mail
  debconf: name=exim4                                                          
           question='{{ item.question }}'                                        
           value='{{ item.value }}'                                              
           vtype='{{ item.vtype }}'                                              
  with_items:                                                                    
      "{{ exim4.config }}"
  notify: restart exim4-config

- name: Install requirements (Debian)
  apt: name={{item}} state=present
  with_items:
  - exim4
  - mailutils
  - alpine

- name: No longer need sendmail and/or postfix (Debian)
  apt: name={{item}} state=absent
  with_items:
  - sendmail-base
  - sendmail-bin
  - postfix
